import { computeDerivedParams } from './orbital-mechanics'
import { computePowerAnalysis, totalAvgPowerDraw, subsystemAvgPower } from './power-budget'
import { predictPasses, computePassMetrics } from './pass-prediction'
import { estimateLifetime, checkCompliance, computeBallisticCoefficient } from './orbital-lifetime'
import { computeConstellationMetrics } from './constellation'
import { computeDeltaVBudget, tsiolkovskyDeltaV } from './delta-v'
import { computeRadiationEnvironment } from './radiation'
import { R_EARTH_EQUATORIAL } from './constants'
import { computeEOAnalysis } from './payload-eo'
import { computeSARAnalysis } from './payload-sar'
import { computeSATCOMAnalysis } from './payload-satcom'
import { computeLagrangeResult } from './lagrange'
import { computeLunarResult } from './lunar-transfer'
import { computeInterplanetaryResult } from './interplanetary'
import { PLANET_DATA } from './beyond-leo-constants'

interface ReportState {
  elements: any
  mission: any
  groundStations: any[]
  subsystems: any[]
  degradationRate: number
  walkerParams: any
  propulsion?: any
  maneuvers?: any
  shieldingThicknessMm?: number
  payloadType?: string
  payloadShared?: any
  payloadEO?: any
  payloadSAR?: any
  payloadSATCOM?: any
  beyondLeo?: any
}

export async function generateMissionReport(state: ReportState): Promise<void> {
  // Dynamic import to code-split jspdf (~300KB)
  const { jsPDF } = await import('jspdf')
  const autoTableModule = await import('jspdf-autotable')
  // jspdf-autotable extends jsPDF prototype via side-effect import
  const autoTable = autoTableModule.default

  const doc = new jsPDF('p', 'mm', 'a4')
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 15
  const contentWidth = pageWidth - 2 * margin
  let y = margin

  const BLUE = [59, 130, 246] as const // accent-blue
  const GRAY = [107, 114, 128] as const
  const DARK = [51, 51, 51] as const

  // ─── Helper functions ───

  function addPageHeader() {
    doc.setFillColor(BLUE[0], BLUE[1], BLUE[2])
    doc.rect(margin, margin, 8, 8, 'F')
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(DARK[0], DARK[1], DARK[2])
    doc.text('ORBITFORGE', margin + 12, margin + 6)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(GRAY[0], GRAY[1], GRAY[2])
    doc.text('Mission Design Report', margin + 12, margin + 10)
    y = margin + 16
  }

  function addSectionTitle(title: string) {
    checkPageBreak(12)
    doc.setFillColor(BLUE[0], BLUE[1], BLUE[2])
    doc.rect(margin, y, contentWidth, 0.5, 'F')
    y += 3
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(BLUE[0], BLUE[1], BLUE[2])
    doc.text(title.toUpperCase(), margin, y + 4)
    y += 10
    doc.setTextColor(DARK[0], DARK[1], DARK[2])
  }

  function addTable(headers: string[], rows: string[][]) {
    checkPageBreak(20)
    autoTable(doc, {
      startY: y,
      head: [headers],
      body: rows,
      margin: { left: margin, right: margin },
      styles: {
        fontSize: 8,
        cellPadding: 2,
        font: 'courier',
        textColor: [51, 51, 51],
        lineColor: [220, 220, 220],
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: [59, 130, 246],
        textColor: [255, 255, 255],
        font: 'helvetica',
        fontStyle: 'bold',
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [248, 249, 250],
      },
      didDrawPage: () => {
        addFooter()
      },
    })
    y = (doc as any).lastAutoTable.finalY + 8
  }

  function addKeyValue(label: string, value: string) {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(GRAY[0], GRAY[1], GRAY[2])
    doc.text(label + ':', margin, y)
    doc.setFont('courier', 'normal')
    doc.setTextColor(DARK[0], DARK[1], DARK[2])
    doc.text(value, margin + 45, y)
    y += 5
  }

  function addFooter() {
    const pageHeight = doc.internal.pageSize.getHeight()
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(GRAY[0], GRAY[1], GRAY[2])
    doc.text(
      'Generated by OrbitForge \u2014 North Star AI Solutions',
      margin,
      pageHeight - 8
    )
    doc.text(
      `Page ${doc.getNumberOfPages()}`,
      pageWidth - margin,
      pageHeight - 8,
      { align: 'right' }
    )
  }

  function checkPageBreak(neededSpace: number) {
    const pageHeight = doc.internal.pageSize.getHeight()
    if (y + neededSpace > pageHeight - 20) {
      addFooter()
      doc.addPage()
      y = margin
    }
  }

  // ─── Compute all data from state ───

  const { elements, mission, groundStations, subsystems, degradationRate, walkerParams } = state
  const derivedParams = computeDerivedParams(elements)
  const avgAlt = elements.semiMajorAxis - R_EARTH_EQUATORIAL

  // Power analysis
  const powerAnalysis = computePowerAnalysis(
    elements,
    mission.spacecraft,
    subsystems,
    mission.lifetimeTarget,
  )

  // Pass prediction (3 days)
  const passes = predictPasses(elements, mission.epoch, groundStations, 3)
  const passMetrics = computePassMetrics(passes, 3, mission.spacecraft.dataRate)

  // Lifetime
  const crossSection = mission.spacecraft.crossSectionArea
  const bStar = computeBallisticCoefficient(mission.spacecraft.mass, crossSection, mission.spacecraft.dragCoefficient)
  const lifetimeDays = estimateLifetime(avgAlt, bStar, 'moderate')
  const compliance = checkCompliance(avgAlt, bStar, 'moderate')

  // Constellation — use orbit tab values when synced
  const effectiveWalkerParams = walkerParams.syncWithOrbit
    ? { ...walkerParams, altitude: Math.round(avgAlt), inclination: elements.inclination }
    : walkerParams
  const constellationMetrics = computeConstellationMetrics(effectiveWalkerParams, mission.spacecraft.mass)

  // ─── Build PDF ───

  // Header
  addPageHeader()

  // Mission name and date
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(DARK[0], DARK[1], DARK[2])
  doc.text(mission.name || 'Untitled Mission', margin, y + 4)
  y += 8
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(GRAY[0], GRAY[1], GRAY[2])
  doc.text(`Generated: ${new Date().toISOString().slice(0, 19)} UTC`, margin, y)
  y += 10

  // ─── Section 1: Mission Overview ───
  addSectionTitle('Mission Overview')
  addKeyValue('Mission Name', mission.name || 'Untitled')
  addKeyValue('Mission Type', mission.missionType)
  addKeyValue('Epoch', mission.epoch instanceof Date ? mission.epoch.toISOString().slice(0, 19) + ' UTC' : String(mission.epoch))
  addKeyValue('Lifetime Target', `${mission.lifetimeTarget} years`)
  addKeyValue('CubeSat Size', mission.spacecraft.size)
  addKeyValue('Mass', `${mission.spacecraft.mass} kg`)
  addKeyValue('Solar Panels', `${mission.spacecraft.solarPanelConfig} (${mission.spacecraft.solarPanelArea} m\u00B2)`)
  addKeyValue('Battery', `${mission.spacecraft.batteryCapacity} Wh`)
  addKeyValue('Antenna', `${mission.spacecraft.antennaType} (${mission.spacecraft.antennaGain} dBi)`)
  addKeyValue('Frequency', mission.spacecraft.frequencyBand)
  addKeyValue('TX Power', `${mission.spacecraft.transmitPower} W`)
  addKeyValue('Data Rate', `${mission.spacecraft.dataRate} kbps`)

  // ─── Section 2: Orbit Design ───
  addSectionTitle('Orbit Design')

  addTable(
    ['Parameter', 'Value'],
    [
      ['Semi-major Axis', `${elements.semiMajorAxis.toFixed(3)} km`],
      ['Eccentricity', elements.eccentricity.toFixed(6)],
      ['Inclination', `${elements.inclination.toFixed(4)}\u00B0`],
      ['RAAN', `${elements.raan.toFixed(4)}\u00B0`],
      ['Arg. of Perigee', `${elements.argOfPerigee.toFixed(4)}\u00B0`],
      ['True Anomaly', `${elements.trueAnomaly.toFixed(4)}\u00B0`],
    ]
  )

  addTable(
    ['Derived Parameter', 'Value'],
    [
      ['Orbital Period', `${(derivedParams.period / 60).toFixed(2)} min`],
      ['Perigee Altitude', `${derivedParams.periapsisAlt.toFixed(1)} km`],
      ['Apogee Altitude', `${derivedParams.apoapsisAlt.toFixed(1)} km`],
      ['V at Perigee', `${derivedParams.velocityPerigee.toFixed(3)} km/s`],
      ['V at Apogee', `${derivedParams.velocityApogee.toFixed(3)} km/s`],
      ['Eclipse Fraction', `${(derivedParams.eclipseFraction * 100).toFixed(1)}%`],
      ['Avg Eclipse Duration', `${(derivedParams.avgEclipseDuration / 60).toFixed(1)} min`],
      ['RAAN Drift', `${derivedParams.raanDrift.toFixed(4)}\u00B0/day`],
      ['Revolutions/Day', derivedParams.revsPerDay.toFixed(2)],
    ]
  )

  // ─── Section 3: Power Budget ───
  addSectionTitle('Power Budget')

  addTable(
    ['Subsystem', 'Mode', 'Power (W)', 'Duty (%)', 'Avg Power (W)'],
    [
      ...subsystems.map((s: any) => [
        s.name,
        s.mode,
        s.powerW.toFixed(1),
        (Math.min(1, Math.max(0, s.dutyCycle)) * 100).toFixed(0),
        subsystemAvgPower(s).toFixed(2),
      ]),
      ['TOTAL', '', '', '', totalAvgPowerDraw(subsystems).toFixed(2)],
    ]
  )

  addTable(
    ['Power Metric', 'Value'],
    [
      ['Peak Solar Power', `${powerAnalysis.peakSolarPower.toFixed(1)} W`],
      ['BOL Avg Generation', `${powerAnalysis.avgPowerGeneration.toFixed(2)} W`],
      ['Avg Consumption', `${powerAnalysis.avgPowerConsumption.toFixed(2)} W`],
      ['BOL Power Margin', `${(powerAnalysis.powerMargin * 100).toFixed(1)}% (${powerAnalysis.marginStatus})`],
      ['EOL Power Margin', `${(powerAnalysis.eolMargin * 100).toFixed(1)}% (${powerAnalysis.eolMarginStatus})`],
      ['Battery DoD/Orbit', `${(powerAnalysis.batteryDoD * 100).toFixed(1)}% (${powerAnalysis.dodStatus})`],
      ['Degradation Rate', `${(degradationRate * 100).toFixed(1)}%/year`],
    ]
  )

  // ─── Section 4: Ground Passes ───
  addSectionTitle('Ground Station Passes')

  addKeyValue('Prediction Window', `3 days from epoch`)
  addKeyValue('Total Passes', `${passes.length}`)
  addKeyValue('Passes/Day', passMetrics.totalPassesPerDay.toFixed(1))
  addKeyValue('Avg Duration', `${passMetrics.avgPassDurationMin.toFixed(1)} min`)
  addKeyValue('Max Contact Gap', `${passMetrics.maxGapHours.toFixed(1)} hrs`)
  addKeyValue('Daily Data Volume', `${passMetrics.dailyDataMB.toFixed(1)} MB`)

  if (passes.length > 0) {
    const topPasses = passes.slice(0, 15)
    addTable(
      ['Station', 'AOS (UTC)', 'Duration (min)', 'Max El (\u00B0)', 'Quality'],
      topPasses.map(p => [
        p.station,
        p.aos.toISOString().slice(0, 19),
        (p.durationSec / 60).toFixed(1),
        p.maxElevation.toFixed(1),
        p.quality,
      ])
    )
  }

  // ─── Section 5: Ground Stations ───
  addSectionTitle('Ground Station Network')

  addTable(
    ['Station', 'Latitude', 'Longitude', 'Min Elevation', 'Active'],
    groundStations.map((gs: any) => [
      gs.name,
      `${gs.lat.toFixed(2)}\u00B0`,
      `${gs.lon.toFixed(2)}\u00B0`,
      `${gs.minElevation}\u00B0`,
      gs.active ? 'Yes' : 'No',
    ])
  )

  // ─── Section 6: Orbital Lifetime ───
  addSectionTitle('Orbital Lifetime & Compliance')

  addKeyValue('Estimated Lifetime', lifetimeDays > 36500 ? '> 100 years' : `${(lifetimeDays / 365.25).toFixed(1)} years (${lifetimeDays} days)`)
  addKeyValue('25-Year Rule (IADC)', compliance.lifetime25Year ? 'COMPLIANT' : 'NON-COMPLIANT')
  addKeyValue('5-Year Rule (FCC)', compliance.lifetime5Year ? 'COMPLIANT' : 'NON-COMPLIANT')
  if (compliance.recommendation) {
    checkPageBreak(10)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(GRAY[0], GRAY[1], GRAY[2])
    const lines = doc.splitTextToSize(`Recommendation: ${compliance.recommendation}`, contentWidth)
    doc.text(lines, margin, y)
    y += lines.length * 4 + 4
  }

  // ─── Section 7: Constellation ───
  if (effectiveWalkerParams && effectiveWalkerParams.totalSats > 1) {
    addSectionTitle('Constellation Design')

    addKeyValue('Pattern', `Walker ${effectiveWalkerParams.type === 'delta' ? 'Delta' : 'Star'} ${effectiveWalkerParams.totalSats}/${effectiveWalkerParams.planes}/${effectiveWalkerParams.phasing}`)
    addKeyValue('Altitude', `${effectiveWalkerParams.altitude} km`)
    addKeyValue('Inclination', `${effectiveWalkerParams.inclination}\u00B0`)
    addKeyValue('Total Satellites', `${constellationMetrics.totalSatellites}`)
    addKeyValue('Sats/Plane', `${constellationMetrics.satsPerPlane}`)
    addKeyValue('Total Mass', `${constellationMetrics.totalMass.toFixed(0)} kg`)
    addKeyValue('Orbital Period', `${constellationMetrics.orbitalPeriodMin.toFixed(1)} min`)
    addKeyValue('Coverage Band', `${constellationMetrics.coverageLatBand.min.toFixed(0)}\u00B0 to ${constellationMetrics.coverageLatBand.max.toFixed(0)}\u00B0`)
  }

  // ─── Section 8: Delta-V Budget ───
  if (state.propulsion && state.propulsion.type !== 'none') {
    addSectionTitle('Delta-V Budget')

    const dvManeuvers = state.maneuvers || []
    const dvBudget = computeDeltaVBudget(
      state.propulsion,
      dvManeuvers,
      mission.spacecraft.mass,
      avgAlt,
      mission.lifetimeTarget,
      bStar,
    )

    addKeyValue('Propulsion Type', state.propulsion.type)
    addKeyValue('Specific Impulse', `${state.propulsion.specificImpulse} s`)
    addKeyValue('Propellant Mass', `${state.propulsion.propellantMass} kg`)
    addKeyValue('Dry Mass', `${mission.spacecraft.mass} kg`)
    addKeyValue('Wet Mass', `${(mission.spacecraft.mass + state.propulsion.propellantMass).toFixed(2)} kg`)
    addKeyValue('Mass Ratio', dvBudget.massRatio.toFixed(3))
    addKeyValue('Available ΔV', `${dvBudget.availableDeltaV.toFixed(1)} m/s`)
    addKeyValue('Required ΔV', `${dvBudget.totalRequiredDeltaV.toFixed(1)} m/s`)
    addKeyValue('ΔV Margin', `${dvBudget.marginDeltaV.toFixed(1)} m/s (${(dvBudget.marginPercent * 100).toFixed(1)}%) — ${dvBudget.marginStatus}`)

    addTable(
      ['Maneuver', 'ΔV (m/s)', 'Propellant (kg)'],
      dvBudget.maneuverBreakdown.map((m) => [
        m.name,
        m.deltaV.toFixed(1),
        m.propellantKg.toFixed(4),
      ])
    )
  }

  // ─── Section 9: Radiation Environment ───
  const shieldingMm = state.shieldingThicknessMm ?? 1
  const rad = computeRadiationEnvironment(avgAlt, elements.inclination, shieldingMm, mission.lifetimeTarget)

  addSectionTitle('Radiation Environment')
  addKeyValue('Altitude', `${avgAlt.toFixed(0)} km`)
  addKeyValue('Inclination', `${elements.inclination.toFixed(1)}°`)
  addKeyValue('Al Shielding', `${shieldingMm} mm`)
  addKeyValue('Belt Region', rad.beltRegion)
  addKeyValue('SAA Exposure', rad.saaExposure)
  addKeyValue('Unshielded Dose', `${rad.unshieldedDoseKradPerYear.toFixed(2)} krad/yr`)
  addKeyValue('Shielded Dose', `${rad.shieldedDoseKradPerYear.toFixed(2)} krad/yr`)
  addKeyValue('Mission Total Dose', `${rad.missionTotalDoseKrad.toFixed(2)} krad`)
  addKeyValue('Component Guidance', `${rad.componentRecommendation} (${rad.componentStatus})`)

  // ─── Section 10: Payload Analysis ───
  if (state.payloadType && state.payloadShared) {
    addSectionTitle('Payload Analysis')

    const pShared = state.payloadShared
    addKeyValue('Payload Type', state.payloadType.toUpperCase())
    addKeyValue('Payload Name', pShared.name || 'Unnamed')
    addKeyValue('Mass', `${pShared.mass} kg`)
    addKeyValue('Peak Power', `${pShared.powerPeak} W`)
    addKeyValue('Avg Power', `${pShared.powerAvg} W`)
    addKeyValue('Duty Cycle', `${(pShared.dutyCycle * 100).toFixed(0)}%`)
    addKeyValue('Data Rate', `${pShared.dataRate} Mbps`)
    addKeyValue('Storage', `${pShared.storageCapacity} GB`)

    if (state.payloadType === 'earth-observation' && state.payloadEO) {
      const eoResult = computeEOAnalysis(state.payloadEO, pShared, avgAlt, elements.inclination)
      addTable(
        ['EO Metric', 'Value'],
        [
          ['GSD (Nadir)', `${eoResult.gsdNadir.toFixed(2)} m`],
          ['GSD (Off-Nadir)', `${eoResult.gsdOffNadir.toFixed(2)} m`],
          ['Swath Width', `${eoResult.swathWidth.toFixed(1)} km`],
          ['FOV', `${eoResult.fovCrossTrack.toFixed(2)}°`],
          ['IFOV', `${eoResult.ifov.toFixed(1)} μrad`],
          ['F-number', `f/${eoResult.fNumber.toFixed(1)}`],
          ['SNR', `${eoResult.snr.toFixed(0)}`],
          ['Daily Coverage', `${eoResult.dailyImagingCapacity.toFixed(0)} km²`],
          ['Revisit Time', `${eoResult.revisitTime.toFixed(1)} days`],
          ['Data Volume/Day', `${eoResult.dataVolumePerDay.toFixed(1)} GB`],
        ]
      )
    }

    if (state.payloadType === 'sar' && state.payloadSAR) {
      const sarResult = computeSARAnalysis(state.payloadSAR, pShared, avgAlt)
      addTable(
        ['SAR Metric', 'Value'],
        [
          ['Wavelength', `${(sarResult.wavelength * 100).toFixed(2)} cm`],
          ['Slant Range', `${sarResult.slantRange.toFixed(0)} km`],
          ['Ground Range Res', `${sarResult.groundRangeRes.toFixed(2)} m`],
          ['Azimuth Res', `${sarResult.azimuthRes.toFixed(2)} m`],
          ['Swath Width', `${sarResult.swathWidth.toFixed(1)} km`],
          ['NESZ', `${sarResult.nesz.toFixed(1)} dB`],
          ['Data Rate', `${sarResult.dataRateComputed.toFixed(0)} Mbps`],
          ['PRF Status', sarResult.prfStatus === 'ok' ? 'OK' : sarResult.prfStatus === 'marginal' ? 'MARGINAL' : 'INVALID'],
          ['Coverage Rate', `${sarResult.areaCoverageRate.toFixed(1)} km²/s`],
          ['Data Volume/Day', `${sarResult.dataVolumePerDay.toFixed(1)} GB`],
        ]
      )
    }

    if (state.payloadType === 'satcom' && state.payloadSATCOM) {
      const satcomResult = computeSATCOMAnalysis(state.payloadSATCOM, pShared, avgAlt)
      addTable(
        ['SATCOM Metric', 'Value'],
        [
          ['Sat Antenna Gain', `${satcomResult.satAntennaGain.toFixed(1)} dBi`],
          ['GS Antenna Gain', `${satcomResult.gsAntennaGain.toFixed(1)} dBi`],
          ['EIRP', `${satcomResult.satEIRP.toFixed(1)} dBW`],
          ['G/T', `${satcomResult.gsGOverT.toFixed(1)} dB/K`],
          ['FSPL', `${satcomResult.fspl.toFixed(1)} dB`],
          ['Eb/N0', `${satcomResult.ebN0.toFixed(1)} dB`],
          ['Link Margin', `${satcomResult.linkMargin.toFixed(1)} dB`],
          ['Max Data Rate', `${satcomResult.maxDataRate.toFixed(2)} Mbps`],
          ['Beam Footprint', `${satcomResult.beamFootprintKm.toFixed(0)} km`],
          ['Data Volume/Day', `${satcomResult.dataVolumePerDay.toFixed(2)} GB`],
        ]
      )
    }
  }

  // ─── Section 11: Beyond-LEO Mission Design ───
  if (state.beyondLeo) {
    const bl = state.beyondLeo
    addSectionTitle('Beyond-LEO Mission Design')
    addKeyValue('Mode', bl.mode.charAt(0).toUpperCase() + bl.mode.slice(1))

    if (bl.mode === 'lagrange' && bl.lagrangeParams) {
      const lr = computeLagrangeResult(bl.lagrangeParams)
      addKeyValue('System', bl.lagrangeParams.system === 'SE' ? 'Sun-Earth' : 'Earth-Moon')
      addKeyValue('Lagrange Point', `${bl.lagrangeParams.system}-${bl.lagrangeParams.point}`)
      addKeyValue('Orbit Type', bl.lagrangeParams.orbitType)
      addKeyValue('Departure Altitude', `${bl.lagrangeParams.departureAltKm} km`)
      addKeyValue('Transfer Type', bl.lagrangeParams.transferType)
      addTable(
        ['Metric', 'Value'],
        [
          ['L-Point Distance', `${lr.pointDistanceKm.toLocaleString()} km (${lr.pointDistanceAU.toFixed(4)} AU)`],
          ['Transfer ΔV', `${lr.transferDeltaVms.toFixed(1)} m/s`],
          ['Insertion ΔV', `${lr.insertionDeltaVms.toFixed(1)} m/s`],
          ['Total ΔV', `${lr.totalDeltaVms.toFixed(1)} m/s`],
          ['Transfer Time', `${lr.transferTimeDays.toFixed(1)} days`],
          ['Halo Period', `${lr.haloPeriodDays.toFixed(1)} days`],
          ['Stability', lr.stabilityClass],
          ['Station-Keeping', `${lr.annualStationKeepingMs.toFixed(1)} m/s/yr`],
          ['Comms Distance', `${lr.commsDistanceKm.toLocaleString()} km`],
          ['One-Way Delay', `${lr.commsDelayS.toFixed(2)} s`],
          ['Mission Total ΔV', `${lr.missionTotalDeltaVms.toFixed(1)} m/s`],
        ]
      )
    }

    if (bl.mode === 'lunar' && bl.lunarParams) {
      const lnr = computeLunarResult(bl.lunarParams)
      addKeyValue('Mission Type', bl.lunarParams.missionType)
      addKeyValue('Transfer Type', bl.lunarParams.transferType)
      addKeyValue('Departure Altitude', `${bl.lunarParams.departureAltKm} km`)
      if (bl.lunarParams.missionType !== 'flyby') {
        addKeyValue('Target Orbit Altitude', `${bl.lunarParams.targetOrbitAltKm} km`)
      }
      addTable(
        ['Metric', 'Value'],
        [
          ['TLI ΔV', `${lnr.tliDeltaVms.toFixed(1)} m/s`],
          ['LOI ΔV', `${lnr.loiDeltaVms.toFixed(1)} m/s`],
          ['Total ΔV', `${lnr.totalDeltaVms.toFixed(1)} m/s`],
          ['Transfer Time', `${lnr.transferTimeDays.toFixed(1)} days`],
          ['Phase Angle', `${lnr.phaseAngleDeg.toFixed(1)}°`],
          ['Lunar Orbit Period', `${lnr.lunarOrbitPeriodMin.toFixed(1)} min`],
          ['Propellant Required', `${lnr.propellantRequiredKg.toFixed(2)} kg`],
          ['One-Way Delay', `${lnr.commDelayS.toFixed(2)} s`],
        ]
      )
    }

    if (bl.mode === 'interplanetary' && bl.interplanetaryParams) {
      const ip = bl.interplanetaryParams
      const ir = computeInterplanetaryResult(ip)
      const pd = PLANET_DATA[ip.targetBody as keyof typeof PLANET_DATA]
      addKeyValue('Target', pd?.name ?? ip.targetBody)
      addKeyValue('Mission Type', ip.missionType)
      addKeyValue('Transfer Type', ip.transferType)
      addKeyValue('Departure Altitude', `${ip.departureAltKm} km`)
      addTable(
        ['Metric', 'Value'],
        [
          ['C3', `${ir.c3Km2s2.toFixed(2)} km²/s²`],
          ['Departure ΔV', `${ir.departureDeltaVms.toFixed(1)} m/s`],
          ['Arrival V∞', `${ir.arrivalVinfKms.toFixed(2)} km/s`],
          ['Insertion ΔV', `${ir.arrivalInsertionDeltaVms.toFixed(1)} m/s`],
          ['Total ΔV', `${ir.totalDeltaVms.toFixed(1)} m/s`],
          ['Transfer Time', `${ir.transferTimeDays.toFixed(0)} days`],
          ['Comms Distance', `${ir.commsDistanceAU.toFixed(2)} AU`],
          ['One-Way Delay', `${(ir.commsDelayS / 60).toFixed(1)} min`],
        ]
      )
    }
  }

  // Add footer to last page
  addFooter()

  // Save
  const filename = `${(mission.name || 'OrbitForge_Report').replace(/\s+/g, '_')}_Report.pdf`
  doc.save(filename)
}
